[package]
name = "web_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "web_proc_macros"
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = "1.0"
quote= "1.0"
proc-macro2 = "1.0"
